### ISSUE TITLE
warp already supports create account and fund it in 1 tx, so we don't need to create account in separate tx now

### ISSUE THREAD

**Issue by eng4753** [llllllluc/cosmos-examples#2]
in the past, for a limit order job, we need to send 1 tx to create a warp account, and send another tx to fund it and create the job. because in order to fund it we need to know the warp account in advance. 

now warp supports create account with fund (`create_account` can act as fund when account already exists), we only need 1 tx no matter user has warp account or not

**Comment by dev8723** [comment]
done
